GET localhost:8080/api/destination

###
GET localhost:8080/api/destination/getById/1

###
POST localhost:8080/api/destination/create
Content-Type: application/json

{
  "street": "Wunderstraße",
  "streetNo": 1,
  "place": "Leonding",
  "zip": 1234
}

###
PUT localhost:8080/api/destination/updateById
Content-Type: application/json

{
  "id": 1,
  "street": "Wunderstraße",
  "streetNo": 1,
  "place": "Leonding",
  "zip": 1234
}
