GET localhost:8080/api/booking

###
GET localhost:8080/api/booking/getById/1

###
POST localhost:8080/api/booking/create
Content-Type: application/json

{
  "person": "Susi",
  "trip": 1
}

###
PUT localhost:8080/api/bus/updateById
Content-Type: application/json

{
  "id": 1,
  "person": "Susi",
  "trip": 1
}
