GET localhost:8080/api/bus

###
GET localhost:8080/api/bus/getById/1

###
POST localhost:8080/api/bus/create
Content-Type: application/json

{
  "seats": 12
}

###
PUT localhost:8080/api/bus/updateById
Content-Type: application/json

{
  "id": 1,
  "seats": 5

}

